### ISSUE TITLE
All pages

### ISSUE THREAD

**Issue by Userpete** [dparker1005/night-mode#3]
Great Script, but is there any way to have it working on all pages instead of having to switch it on on every page? I don't want to use the time settings as time zones vary

Many thanks

**Comment by dparker1005** [comment]
Hello, I have just updated the plugin to use the user's local time, which  should help with the time zone issues, and also to keep night mode enabled if the user enables it until they disable it.

**Comment by dparker1005** [comment]
Cookie-saving functionality was added a few commits ago
